### ISSUE TITLE
[MBP-16] Cannot Resume after suspend

### ISSUE THREAD

**Issue by swinder0161** [t2linux/T2-Ubuntu#11]
Once I suspend my machine, cannot resume back.

I am not sure if suspend is even going through or not, the screen goes black and I feel no fan or other vibration also.

Is it same issue as the author has written that shutdown hangs?

Anyone else facing the same issue?

**Comment by marcosfad** [comment]
Hi, we are all experiencing the same issue. There is no fix for that at the moment.
I can recommend you to join the discord channel.

**Comment by reynaldliu** [comment]
i am same

**Comment by doublebyte1** [comment]
Hi ! I am also experiencing this issue. @marcosfad can you share the address of the discord channel? Thank you

**Comment by networkException** [comment]
This is a link to the server https://discord.com/invite/68MRhQu

**Comment by AdityaGarg8** [comment]
Suspend has been finally fixed
