### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by ghazel** [t2linux/T2-Ubuntu#12]
MacbookPro16,1

There might be a simple patch to get it working: https://github.com/Dunedan/mbp-2016-linux#bluetooth

**Comment by marcosfad** [comment]
Hi, unfortunately that solution is already part of the kernel. That looks now like this:

```
	/* wait for device to power on and come out of reset */
	usleep_range(100000, 120000);

	dev->res_enabled = powered;
```

**Comment by AdityaGarg8** [comment]
Bluetooth was fixed long ago.
