### ISSUE TITLE
Network Manager not running

### ISSUE THREAD

**Issue by ceinem** [t2linux/T2-Ubuntu#17]
Hi, 
is anyone else having issues with the network manager? Sometimes when I plug in a USB-Wifi Dongle the Network Manager appears to crash and I just get error messages "Network Manager is not running". 
I also seem to not be able to start it again, only rebooting the system fixes this. 

I'm using a mbp16,1

**Comment by marcosfad** [comment]
Try installing iwd (`apt-get install iwd`) and configuring to be use in the Network Manager. See:
https://github.com/marcosfad/mbp-ubuntu/blob/master/files/chroot_build.sh#L181

**Comment by AdityaGarg8** [comment]
As per the current scenario, network manager works perfectly.
