### ISSUE TITLE
Shutting down not working

### ISSUE THREAD

**Issue by marcosfad** [t2linux/T2-Ubuntu#2]
I'm having an issue shutting down ubuntu. Shutdown process look ok. No message whatsoever is shown. Screen goes black, but the fan keeps on working.

Does anybody is experiencing a similar issue?

**Comment by ceinem** [comment]
Yes, I have the same issue. After some time it would then basically crash and reboot the system. It automatically boots into macOS in my case, and displays an error message that the computer had to be rebooted due to an issue. 
I'll try to export the detailed error report next time it happens.

**Comment by AdityaGarg8** [comment]
It works now:)
