### ISSUE TITLE
Development boost

### ISSUE THREAD

**Issue by awrelll** [t2linux/T2-Ubuntu#22]
Hello,
Are there any initiatives to fund development of the `mbp-ubuntu` project? I feel like BigSur will create a huge wave of mbp-Ubuntu users.
Cheers!

**Comment by marcosfad** [comment]
Hi awrell, that is very kind of you. You should think about supporting http://t2linux.org. I think soon will come a GitHub Sponsor possibility for the project. Does are the guy doing most of the heavy lifting. I'm just bundling all together.

I'm always happy about a coffee per Paypal, if my repo helps.
