### ISSUE TITLE
no rightclick/scroll on trackpad

### ISSUE THREAD

**Issue by jkrosado** [t2linux/T2-Ubuntu#30]
i can't scroll, or rightclick. seems to be treating the trackpad as a traditional mouse. i'm using my iphone over USB as wifi, and live booting from SD card, so i don't have the option to use an external mouse
version 5.3.19 (not alt)

**Comment by Redecorating** [comment]
This release of the kernel should make the trackpad driver correctly identify your trackpad, enabling right click and scrolling. https://github.com/marcosfad/mbp-ubuntu-kernel/releases/tag/v5.10.47

**Comment by AdityaGarg8** [comment]
Doesn’t seem to be relevant as per the current scenario
