### ISSUE TITLE
MacBook Pro 16,1 Kernel Panic

### ISSUE THREAD

**Issue by Welfordian** [t2linux/T2-Ubuntu#36]
I seem to get to the user details section and then the keyboard & trackpad stops working and the system reboots after about 10 seconds. I have SIP disabled and T2 disabled. Any ideas?

**Comment by networkException** [comment]
What kernel version are you using?

**Comment by networkException** [comment]
Did you use the latest release from github? That would, as the title says, use kernel version 5.8.13, which is considered unstable. I would recommend using [the 5.7.19 release](https://github.com/marcosfad/mbp-ubuntu/releases/tag/v20.04-5.7.19-1) for now and then after installing to take a look at https://wiki.t2linux.org/guides/kernel/ to upgrade the kernel to a non end of life version.

**Comment by sramanujan** [comment]
I have the same issue exact same issue as well. It gets stuck for me a little after the timezone world map screen. First keyboard and touch freeze, and then the machine shuts with the fan going to full speed for a second.

MacbookPro15,1. 

Just like the previous comment says, I used the latest iso.

I am now going to try the 5.7.19 release. Hope it works..
