### ISSUE TITLE
Wi-fi trouble in v20.04-5.10.52

### ISSUE THREAD

**Issue by aksenovan** [t2linux/T2-Ubuntu#46]
I'm trying to install v20.04-5.10.52 ( livecd-5.10.52-mbp-16x-wifi.zip  ) on Macbook:
- MacBook Pro (15-inch, 2019)
- macOS Big Sur 11.5.1
- 2,6 GHz 6x Intel Core i7

After installation as recommended I installed a kernel [v5.13.12-1](https://github.com/AdityaGarg8/T2-Big-Sur-Ubuntu-Kernel/releases/tag/v5.13.12-1) to support wi-fi. But after kernel installation I got no wifi support  as well as a loss of touchbar and keyboard support. 

What could I miss?

**Comment by AdityaGarg8** [comment]
@aksenovan , use https://github.com/marcosfad/mbp-ubuntu/releases/tag/v20.04-5.7.19-1.
It's stable and tried and tested.

**Comment by AdityaGarg8** [comment]
And follow https://wiki.t2linux.org/guides/dkms/ first

**Comment by AdityaGarg8** [comment]
Then upgrade your kernel

**Comment by AdityaGarg8** [comment]
And then follow https://wiki.t2linux.org/guides/wifi/

**Comment by marcosfad** [comment]
Hi, thank you for reporting your issue. I'm working in a new release which hopefully will fix this kind of problems.

**Comment by aksenovan** [comment]
Thanks a lot for your  advice!  v20.04-5.7.19-1 works for me

**Comment by aksenovan** [comment]
There is one curious detail: battery charge level in Ubuntu indicates a value less than real (in MacOS). When charge level is ~87% in Ubuntu,  a MacOS one is 100%

**Comment by AdityaGarg8** [comment]
That's because of battery optimization by T2. You needn't worry much.

**Comment by CR0CKER** [comment]
I'm unable to get wifi to work as well on my MBP 16,2 -- any updated on when a fix may be ready? Looking forward to proceeding with my transition to Linux but can't do it without working wifi and bluetooth. Thanks for your awesome work!

**Comment by AdityaGarg8** [comment]
@CR0CKER , may I know the output of uname -r?

**Comment by CR0CKER** [comment]
@AdityaGarg8 -- that's 5.10.52-mbp-16x-wifi

**Comment by AdityaGarg8** [comment]
@CR0CKER , try https://github.com/AdityaGarg8/T2-Big-Sur-Ubuntu-Kernel/releases/tag/v5.14.9-2

**Comment by AdityaGarg8** [comment]
Bluetooth support for 16,2 has been introduced today and is there in this kernel.

**Comment by AdityaGarg8** [comment]
For wifi you need to get the correct firmware as described on https://wiki.t2linux.org/guides/wifi/

**Comment by CR0CKER** [comment]
Thanks! I'm actually unclear what the instructions on t2linux.org mean -- it says I should "retrieve three of the four files" but I'm not sure how to "retrieve" them (there doesn't seem to be a URL). I was under the impression that downloading and installing the new kernel was enough, but I'm starting to understand that I still need to install the actual drivers separately after downloading them. Thanks for your help on this.

**Comment by CR0CKER** [comment]
If there will soon be a new version of mbp-ubuntu that already includes these wifi drivers, I'd rather wait then going though these steps manually.

**Comment by AdityaGarg8** [comment]
> If there will soon be a new version of mbp-ubuntu that already includes these wifi drivers, I'd rather wait then going though these steps manually.

These are not the drivers. This is the firmware. It is practically not possible to make a common firmware for all models since each model has its own firmware variety and thus this is the only way out. If you are still having issues @CR0CKER , please contact the discord (https://discord.com/invite/68MRhQu). Someone would help you out through the steps there.

**Comment by AdityaGarg8** [comment]
Also, you may contact the discord to get the files retrieved for you.

**Comment by AdityaGarg8** [comment]
There have been significant improvements to the wifi, so I don’t think this issue is relevant now.
