### ISSUE TITLE
Enable multitouch

### ISSUE THREAD

**Issue by thalesmaoa** [t2linux/T2-Ubuntu#64]
I've installed ubuntu and libgesture to enable multitouch. Do you recommend another route? I can't get pinch to work.

**Comment by acheong08** [comment]
Though for Chrome you will need to change the Ozone layer settings in flags

**Comment by acheong08** [comment]
For Ubuntu 20.04 LTS you would want to look at touchegg

**Comment by thalesmaoa** [comment]
@acheong08, unfortunately, touchegg uses xdotool, which presents some delay issues since my keyboard is US and my language is pt-br. Known bug. Do you suggest to upgrade?

**Comment by acheong08** [comment]
I am currently on Ubuntu 21.10 and it works perfectly, though you do have to use apt to install `gnome-shell-extension-desktop-icons-ng` to fix the Desktop. Otherwise desktop icons do not show up.

**Comment by thalesmaoa** [comment]
You made it manually or did you use the iso? I don't know how to went from LTS to 21.10.

**Comment by acheong08** [comment]
https://askubuntu.com/questions/1369423/upgrade-from-ubuntu-20-04-lts-to-ubuntu-21-10

**Comment by acheong08** [comment]
Upgrading might break PPAs. You will have to add them again and reinstall software from said PPAs
