### ISSUE TITLE
Macbook Air 2018 - mic is not working

### ISSUE THREAD

**Issue by javacom** [t2linux/T2-Ubuntu#66]
When doing zoom, the Macbook Air, microphone is not working.  Audio and webcam are OK.

**Comment by Redecorating** [comment]
can you check `cat /proc/cmdline`? If it doesn't contain `iommu=pt` and `intel_iommu=on`, can you follow [this](https://wiki.t2linux.org/guides/audio-config/#enable-pass-through-kernel-parameters), reboot and see if it helps

**Comment by javacom** [comment]
following the post I have edited the grub and regenerate then reboot.  But the internal and external microphone are still not working.

**Comment by acheong08** [comment]
Are you using Pipewire instead of Pulseaudio? It currently works for me using retaining the Pulseaudio configuration.

**Comment by AdityaGarg8** [comment]
There have been updates to the sound configuration files (https://wiki.t2linux.org/guides/audio-config/). Also, its recommended to use pipewire. If you still are facing the issue, please reopen.
