### ISSUE TITLE
Ubuntu Live booting freezes

### ISSUE THREAD

**Issue by aydar-y** [t2linux/T2-Ubuntu#69]
Booting freezes why trying to boot or install Ubuntu from the flashed USB stick (see the screenshot
![photo_2022-05-16 20 43 26](https://user-images.githubusercontent.com/63450341/168652259-6bc539a4-032b-45f5-a132-977d697561a5.jpeg)
)

**Comment by aydar-y** [comment]
It's MacBook Pro (16-inch, 2019) Intel

**Comment by AdityaGarg8** [comment]
What ISO are you using?

**Comment by aydar-y** [comment]
The latest, v20.04-5.17.1-1, ubuntu-20.04.iso downloaded yesterday. The checksum sha256 has also been verified

**Comment by AdityaGarg8** [comment]
Could you try this?
https://github.com/AdityaGarg8/mbp-ubuntu/releases/tag/v20.04-5.17.7

**Comment by aydar-y** [comment]
Tried it. Same result
![photo_2022-05-18 15 41 25](https://user-images.githubusercontent.com/63450341/169041011-60745c82-149e-4dd8-b3c9-6f09c040638b.jpeg)
:

**Comment by aydar-y** [comment]
diskutil list # found which number has the USB
sudo diskutil umountDisk /dev/diskX
sudo dd bs=4096 if=ubuntu-20.04-XXX.iso of=/dev/diskX****

**Comment by AdityaGarg8** [comment]
Could you try using Balena Etcher

**Comment by AdityaGarg8** [comment]
Is your macOS updated?
If yes, then try the 5.7.19-mbp ISO from https://github.com/marcosfad/mbp-ubuntu/releases/tag/v20.04-5.7.19-1

Else, first update macOS and then try your USB stick.

**Comment by aydar-y** [comment]
It's running macOS Big Sur 11.6.6, the latest of Big Sur. Should I update it to Monterrey?

**Comment by AdityaGarg8** [comment]
You may try upgrading to Monterrey.

**Comment by AdityaGarg8** [comment]
or first try https://github.com/marcosfad/mbp-ubuntu/releases/tag/v20.04-5.7.19-1

**Comment by aydar-y** [comment]
Tried everything, updated to Monterrey- same result everywhere, freezing at boot

**Comment by AdityaGarg8** [comment]
Well I made an ISO for 22.04 today.

https://github.com/AdityaGarg8/mbp-ubuntu/releases/tag/v22.04-5.17.9

Maybe it shall work?

Also, @Redecorating , could you help here?

**Comment by AdityaGarg8** [comment]
Also, it's possible that it has something to do with your USB stick, cause these ISOs are tried and tested on many MacBook Pro 16 inch models.

**Comment by aydar-y** [comment]
None of the images worked. It just freezes at that same point. I tried different USB sticks and adapters.

**Comment by AdityaGarg8** [comment]
@Redecorating , could you see the -ENIVAL error shown in the logs

**Comment by mahboobkarimian** [comment]
Did You disable the secure boot and do the preparations as described here: https://wiki.t2linux.org/distributions/ubuntu/installation/ ?

**Comment by aydar-y** [comment]
Of course I did
