### ISSUE TITLE
Keyboard backlight not working

### ISSUE THREAD

**Issue by ceinem** [t2linux/T2-Ubuntu#8]
I'm running this on a MacBookPro16,1, mostly it works really well, with the known issues of WiFi and the Microphone. 
I wanted to know if anyone had issues with the keyboard backlight or got it working? 

It shows the options of changing the backlight brightness on the TouchBar, but they don't do anything in my case.

**Comment by swinder0161** [comment]
Same issue with me on MBP-16,1, someone please help.

**Comment by marcosfad** [comment]
hi, yes. Unfortunately this is also an issue of the 16,1 model. I haven't found I fix yet.

**Comment by reynaldliu** [comment]
HDMI external monitor
`command +p` and push `enter `
Then unplug it, you can restore the display

Or sometimes long press the Power button to turn on the screen for 2 seconds

**Comment by AdityaGarg8** [comment]
The driver for the backlight is now available in the latest kernels
